language: node_js

node_js:
  - 14

cache:
  directories:
    - 'node_modules'

notifications:
  email:
    on_success: never

branches:
  only:
    - master

install:
  - yarn --frozen-lockfile

script:
  - yarn cli
