name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Bootstrap
        run: yarn bootstrap

      - name: Run unit test case
        run: yarn test

      - name: Report coverage
        uses: codecov/codecov-action@v2
